apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: rf1gqkgu2-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rf1gqkgu2-go 
  name: rf1gqkgu2-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: rf1gqkgu2-go 
